import type { Metadata } from "next";
import "./globals.css";
import {LanguageProvider} from "@/context/LanguageContext";
import {getLanguageCookie} from "@/context/action";
import React from "react";

export const metadata: Metadata = {
  title: "Words hotel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const mainLanguage = await getLanguageCookie("main");
    const learnLanguage = await getLanguageCookie("learn");

    return (
        <html lang="ru">
            <body
                className={`antialiased bg-(--background)`}
            >
                <LanguageProvider initialMainLanguage={mainLanguage} initialLearnLanguage={learnLanguage}>
                    {children}
                </LanguageProvider>
            </body>
        </html>
    );
}
